export const COUNTRIES = [
  { value: 'AR', label: 'Argentina' },
  { value: 'BO', label: 'Bolivia' },
  { value: 'BR', label: 'Brasil' },
  { value: 'CL', label: 'Chile' },
  { value: 'CO', label: 'Colombia' },
  { value: 'CR', label: 'Costa Rica' },
  { value: 'EC', label: 'Ecuador' },
  { value: 'SV', label: 'El Salvador' },
  { value: 'GT', label: 'Guatemala' },
  { value: 'HN', label: 'Honduras' },
  { value: 'MX', label: 'México' },
  { value: 'NI', label: 'Nicaragua' },
  { value: 'PA', label: 'Panamá' },
  { value: 'PY', label: 'Paraguay' },
  { value: 'PE', label: 'Perú' },
  { value: 'DO', label: 'República Dominicana' },
  { value: 'UY', label: 'Uruguay' },
  { value: 'VE', label: 'Venezuela' },
  { value: 'ES', label: 'España' },
  { value: 'US', label: 'Estados Unidos' },
]

export const BUSINESS_CATEGORIES = [
  { value: 'automotive', label: 'Automotriz' },
  { value: 'electronics', label: 'Electrónica' },
  { value: 'fashion', label: 'Moda' },
  { value: 'beauty', label: 'Belleza' },
  { value: 'cosmetics', label: 'Cosméticos' },
  { value: 'health', label: 'Salud' },
  { value: 'pharmacy', label: 'Farmacia' },
  { value: 'technology', label: 'Tecnología' },
  { value: 'home', label: 'Hogar' },
  { value: 'furniture', label: 'Muebles' },
  { value: 'construction', label: 'Construcción' },
  { value: 'hardware', label: 'Ferretería' },
  { value: 'food', label: 'Alimentos' },
  { value: 'beverages', label: 'Bebidas' },
  { value: 'restaurant', label: 'Restaurantes' },
  { value: 'education', label: 'Educación' },
  { value: 'sports', label: 'Deportes' },
  { value: 'pets', label: 'Mascotas' },
  { value: 'toys', label: 'Juguetes' },
  { value: 'real_estate', label: 'Inmobiliaria' },
  { value: 'professional', label: 'Servicios' },
  { value: 'financial', label: 'Financiero' },
  { value: 'travel', label: 'Turismo' },
  { value: 'industrial', label: 'Industrial' },
  { value: 'entertainment', label: 'Entretenimiento' },
  { value: 'retail', label: 'Retail / Tienda' },
  { value: 'nonprofit', label: 'ONG / Sin fines de lucro' },
  { value: 'other', label: 'Otro' },
]

export const CAMPAIGN_OBJECTIVES = [
  { value: 'awareness', label: 'Reconocimiento de marca', description: 'Dar a conocer tu negocio' },
  { value: 'traffic', label: 'Tráfico web', description: 'Llevar visitas a tu sitio' },
  { value: 'engagement', label: 'Engagement', description: 'Likes, comentarios y compartidos' },
  { value: 'leads', label: 'Generación de leads', description: 'Captar datos de clientes' },
  { value: 'sales', label: 'Ventas', description: 'Conversiones y compras directas' },
]

export const LANGUAGES = [
  { value: 'es', label: 'Español' },
  { value: 'en', label: 'Inglés' },
  { value: 'pt', label: 'Portugués' },
  { value: 'fr', label: 'Francés' },
  { value: 'it', label: 'Italiano' },
  { value: 'de', label: 'Alemán' },
]

export const GENDER_OPTIONS = [
  { value: 'all', label: 'Todos' },
  { value: 'male', label: 'Hombres' },
  { value: 'female', label: 'Mujeres' },
]

export const CURRENCIES = [
  { value: 'USD', label: 'USD — Dólar' },
  { value: 'MXN', label: 'MXN — Peso Mexicano' },
  { value: 'ARS', label: 'ARS — Peso Argentino' },
  { value: 'COP', label: 'COP — Peso Colombiano' },
  { value: 'CLP', label: 'CLP — Peso Chileno' },
  { value: 'PEN', label: 'PEN — Sol Peruano' },
  { value: 'BRL', label: 'BRL — Real Brasileño' },
  { value: 'PYG', label: '🇵🇾 PYG — Guaraní Paraguayo' },
  { value: 'EUR', label: 'EUR — Euro' },
]

// ── Creative Image Generation ──────────────────────────────────────────────────

export type CreativeModel = 'flux' | 'flux-realism' | 'flux-anime' | 'flux-3d' | 'turbo'
export type CreativeFormat = 'square' | 'landscape' | 'portrait' | 'story'

export interface CreativePreset {
  id: string
  label: string
  description: string
  visualStyle: string           // compact summary sent by client in API body
  advertisingConcept: string    // what the ad should communicate
  environment: string           // scene/setting description
  lightingStyle: string         // lighting approach
  colorStyle: string            // color palette and mood
  defaultModel: CreativeModel
}

export const CREATIVE_PRESETS: CreativePreset[] = [
  {
    id: 'premium-product',
    label: 'Premium Product',
    description: 'Fotografía de producto de lujo',
    visualStyle: 'premium luxury product photography, dark elegant studio, minimal composition',
    advertisingConcept: 'High-end premium product advertisement conveying quality, exclusivity and craftsmanship. Every visual element communicates superiority and superior value. The product is the hero.',
    environment: 'Dark elegant studio with subtle gradient background. Minimal props that complement the product. Premium surface materials such as marble, black glass or brushed metal as base.',
    lightingStyle: 'Professional studio lighting: key light from 45° above, rim light from behind, soft fill light. Creates dramatic shadows that define the product form and reveal texture.',
    colorStyle: 'Rich dark palette: deep blacks, champagne golds, platinum silvers. High contrast between product and background. Luxurious and aspirational.',
    defaultModel: 'flux-realism',
  },
  {
    id: 'luxury-brand',
    label: 'Luxury Brand',
    description: 'Imagen aspiracional y exclusiva',
    visualStyle: 'luxury aspirational brand photography, lifestyle editorial, exclusive high-end atmosphere',
    advertisingConcept: 'Aspirational luxury brand image that makes the viewer desire the lifestyle associated with the product. Emotion and aspiration over function. Dreams and identity.',
    environment: 'Elegant upscale environment: marble surfaces, designer furniture, penthouse settings, or exclusive curated locations. Context reinforces wealth, taste and exclusivity.',
    lightingStyle: 'Soft editorial lighting with golden accents. Warm and inviting yet sophisticated. French window light or warm professional studio setup.',
    colorStyle: 'Warm luxury palette: champagne, warm whites, caramel, deep navy or burgundy. Cohesive color story throughout the entire frame.',
    defaultModel: 'flux-realism',
  },
  {
    id: 'modern-ecommerce',
    label: 'Modern Ecommerce',
    description: 'Producto claro sobre fondo limpio',
    visualStyle: 'clean ecommerce product photography, white or light background, sharp product detail',
    advertisingConcept: 'Clean ecommerce product shot optimized for online shopping. Clarity and accuracy over creative storytelling. Customer sees exactly what they are buying.',
    environment: 'Pure white or very light gray seamless background. Minimal to no props. Product presented clearly, visible in its entirety with all packaging details sharp.',
    lightingStyle: 'Bright even studio lighting eliminating shadows. White box lighting setup. Every product label and surface detail sharp and accurate.',
    colorStyle: 'Clean neutral palette: bright whites, light grays. Colors highlight the product itself rather than the environment.',
    defaultModel: 'flux',
  },
  {
    id: 'minimalist',
    label: 'Minimalist',
    description: 'Composición limpia y elegante',
    visualStyle: 'minimalist photography, generous negative space, clean elegant composition, sophisticated restraint',
    advertisingConcept: 'Less is more. The product speaks for itself with breathing room. Sophisticated restraint that communicates confidence. Maximum space for copy and CTA overlays.',
    environment: 'Vast clean background with generous negative space on one side. Single product, possibly one subtle prop. Space is the message.',
    lightingStyle: 'Soft diffused natural or studio lighting. Very gentle shadows. Even, peaceful, uncluttered illumination.',
    colorStyle: 'Monochromatic or 2-color palette maximum. Whites, light grays, or a single accent color.',
    defaultModel: 'flux',
  },
  {
    id: 'commercial-advertising',
    label: 'Commercial Advertising',
    description: 'Publicidad comercial de alto impacto',
    visualStyle: 'high-impact commercial advertising, bold composition, strong visual hierarchy, promotional energy',
    advertisingConcept: 'High-conversion promotional advertisement with strong visual impact. Communicates value, urgency and clear product benefit. Reserves space for promotional text and CTA overlay.',
    environment: 'Bold studio or dynamic setting with energetic visual elements. Strong composition that draws the eye immediately to the product center.',
    lightingStyle: 'High-key lighting with strong contrasts. Commercial advertising style: bright, clear, impactful and energetic.',
    colorStyle: 'High saturation with bold accent colors. Red, orange or yellow for urgency. High contrast between product and background.',
    defaultModel: 'flux',
  },
  {
    id: 'social-media',
    label: 'Social Media',
    description: 'Optimizado para Instagram y Facebook',
    visualStyle: 'lifestyle social media photography, bright airy aesthetic, Instagram-worthy, high engagement',
    advertisingConcept: 'Instagram and Facebook optimized creative for maximum engagement and shares. Thumb-stopping yet authentic. Makes viewers stop scrolling and desire the product.',
    environment: 'Clean aspirational lifestyle setting: modern surfaces, natural backgrounds, aspirational environments. Context connects emotionally with the target audience.',
    lightingStyle: 'Soft natural window light or warm golden-hour lighting. Bright, airy and approachable. Instagram-worthy illumination.',
    colorStyle: 'Fresh modern palette: clean whites, warm neutrals, accent tones. Cohesive and editorial like a curated feed.',
    defaultModel: 'flux',
  },
  {
    id: 'fashion',
    label: 'Fashion',
    description: 'Moda, ropa y accesorios',
    visualStyle: 'fashion editorial photography, styled composition, runway or lifestyle editorial, magazine quality',
    advertisingConcept: 'Fashion editorial advertisement selling a style and attitude, not just a product. The item embodies an identity and aspiration. Fashion-forward and aspirational.',
    environment: 'Fashion editorial setting: studio with textured backdrop, urban street scene, architectural environment, or lifestyle context matching the brand positioning.',
    lightingStyle: 'Fashion photography lighting: dramatic editorial for luxury, natural light for lifestyle, bright studio for commercial. Enhances texture and color vibrancy.',
    colorStyle: 'Color palette aligned with the season and brand. High fashion: bold contrast. Casual: warm natural tones. Luxury: muted and elegant.',
    defaultModel: 'flux-realism',
  },
  {
    id: 'beauty-cosmetics',
    label: 'Beauty & Cosmetics',
    description: 'Belleza, cosméticos y skincare',
    visualStyle: 'beauty cosmetics photography, flawless product display, elegant feminine, glowing textures',
    advertisingConcept: 'Beauty and cosmetics advertisement focused on glamour, desire and transformation. The product promises a better version of the customer. Sensorial and aspirational.',
    environment: 'Feminine elegant environment: white marble surface, soft florals, luxury vanity setting, or cosmetic flat lay. Textures of glass, silk and crystal in the frame.',
    lightingStyle: 'Soft beauty lighting that makes textures glow: glass elegantly reflects light, packaging shines, liquid textures catch beautiful light. Warm or cool glow.',
    colorStyle: 'Feminine luxury palette: rose golds, soft pinks, clean whites, pearl tones, lavender. Or sophisticated editorial black and white.',
    defaultModel: 'flux-realism',
  },
  {
    id: 'food-beverage',
    label: 'Food & Beverage',
    description: 'Alimentos, bebidas y gastronomía',
    visualStyle: 'food photography, appetizing professional styling, gastronomy photography, mouth-watering quality',
    advertisingConcept: 'Mouth-watering food photography that makes viewers crave the product immediately. All senses engaged through visual storytelling. Freshness and appetite appeal.',
    environment: 'Appetizing food setting: restaurant table, kitchen counter, rustic wooden surface, or modern plating. Props: plates, cutlery, fresh ingredients that complement the food.',
    lightingStyle: 'Warm food photography lighting: overhead natural light or angled soft diffused light. Highlights textures, steam, moisture and vibrant colors.',
    colorStyle: 'Warm appetizing palette: warm whites, natural wood tones, fresh ingredient colors. Vibrancy that makes food look fresh, delicious and irresistible.',
    defaultModel: 'flux-realism',
  },
  {
    id: 'technology',
    label: 'Technology',
    description: 'Electrónica, gadgets y software',
    visualStyle: 'technology product photography, sleek modern studio, dark background, screen glow, clean tech aesthetic',
    advertisingConcept: 'Technology product advertisement communicating innovation, performance and modernity. The product feels powerful, precise and cutting-edge. Future-forward.',
    environment: 'Clean modern tech environment: dark studio with subtle blue or cyan ambient light, reflective dark surfaces, minimalist tech workspace or abstract tech context.',
    lightingStyle: 'Tech photography lighting: subtle LED color accent lighting in blue or cyan, screen glow effect, clean specular highlights on metallic and glass surfaces.',
    colorStyle: 'Modern tech palette: dark backgrounds, blue or cyan accents, white highlights, metallic silver. Clean, futuristic and innovative.',
    defaultModel: 'flux-realism',
  },
  {
    id: 'furniture-home',
    label: 'Furniture & Home',
    description: 'Muebles, hogar y decoración',
    visualStyle: 'interior design photography, lifestyle home staging, architectural photography, warm cozy atmosphere',
    advertisingConcept: 'Interior lifestyle advertisement selling a feeling of home, comfort and style. The product is shown in a desirable living space the customer wants to inhabit.',
    environment: 'Styled home interior: living room, bedroom, dining area or kitchen. Carefully curated decor, natural light from large windows, plants and lifestyle props.',
    lightingStyle: 'Warm natural interior lighting: large windows, late afternoon golden light, warm white interior lamps. Creates an inviting and cozy ambiance.',
    colorStyle: 'Warm interior palette: natural wood tones, warm whites and creams, terracotta, sage green, or neutral grays. Scandinavian or Mediterranean inspired.',
    defaultModel: 'flux-realism',
  },
  {
    id: 'healthcare',
    label: 'Healthcare',
    description: 'Salud, farmacia y bienestar',
    visualStyle: 'healthcare product photography, clean clinical trust, wellness photography, professional and hygienic',
    advertisingConcept: 'Healthcare advertisement communicating trust, safety, efficacy and care. Balances clinical authority with human warmth. Radiates reliability and professionalism.',
    environment: 'Clean clinical or wellness environment: bright white clinical studio, natural wellness setting, or calm medical office. Fresh, sterile and trustworthy context.',
    lightingStyle: 'Bright clean clinical lighting: even white illumination, no harsh shadows, fresh and hygienic atmosphere. Radiates cleanliness and professional trust.',
    colorStyle: 'Healthcare palette: clean whites, medical blues and greens, soft teal. Colors associated with health, trust and cleanliness.',
    defaultModel: 'flux',
  },
  {
    id: 'real-estate',
    label: 'Real Estate',
    description: 'Inmobiliaria y arquitectura',
    visualStyle: 'real estate photography, architectural photography, luxury property interior, bright wide angle',
    advertisingConcept: 'Real estate advertisement making properties feel aspirational and desirable. Highlights space, light and lifestyle potential. Inspires desire to live there.',
    environment: 'Property interior or exterior: modern apartment, luxury house, commercial space, or development rendering. Pristine staging with lifestyle props.',
    lightingStyle: 'Bright real estate photography: blended natural and artificial light, blue sky exterior, warm interior lighting that makes spaces feel inviting and spacious.',
    colorStyle: 'Neutral real estate palette: warm whites, light grays, natural wood accents. Clean and universally appealing.',
    defaultModel: 'flux-realism',
  },
  {
    id: 'automotive',
    label: 'Automotriz',
    description: 'Autos, repuestos y servicios vehiculares',
    visualStyle: 'automotive photography, dark studio, metallic reflections, cinematic dramatic lighting, performance',
    advertisingConcept: 'Automotive advertisement designed to inspire desire, trust and performance. The product feels powerful, reliable and engineered to precision. Speed and engineering excellence.',
    environment: 'Automotive setting: professional showroom, dark dramatic studio, race track, or urban street environment. Vehicles, tools or industrial automotive props as context.',
    lightingStyle: 'Cinematic automotive lighting: dramatic studio with metal reflections, rim lighting from behind, specular highlights on metallic and chrome surfaces. Dynamic and powerful.',
    colorStyle: 'Automotive palette: deep blacks, metallic silvers and chrome, red or orange accents. High contrast, dramatic and performance-driven.',
    defaultModel: 'flux-realism',
  },
  {
    id: 'industrial',
    label: 'Industrial',
    description: 'Industria, construcción y ferretería',
    visualStyle: 'industrial photography, authentic professional environment, rugged and reliable, heavy-duty tools',
    advertisingConcept: 'Industrial advertisement communicating durability, reliability and professional performance. Appeals to professionals who demand products that work in tough conditions.',
    environment: 'Industrial environment: organized professional workshop, construction site, factory floor, or job site. Industrial equipment, tools and materials as authentic context.',
    lightingStyle: 'Authentic industrial lighting: overhead industrial lamps, natural skylights, realistic work environment atmosphere. Documentary photography credibility.',
    colorStyle: 'Industrial palette: steel grays, safety yellows and oranges, worn metals, earth tones. Professional, rugged and trustworthy.',
    defaultModel: 'flux-realism',
  },
  {
    id: 'corporate',
    label: 'Corporate',
    description: 'Servicios empresariales y B2B',
    visualStyle: 'corporate professional photography, clean business environment, trust authority, modern office',
    advertisingConcept: 'Corporate advertisement building trust, credibility and professional authority. Conservative yet modern. Speaks directly to business decision-makers and professionals.',
    environment: 'Professional business environment: modern office, conference room, corporate lobby, or clean desk workspace. Subtle branded elements and premium office props.',
    lightingStyle: 'Professional corporate lighting: clean even illumination, natural office lighting, professional and flattering. No dramatic or distracting shadows.',
    colorStyle: 'Corporate palette: navy blues, professional grays, clean whites, subtle accent colors. Conservative, authoritative and credible.',
    defaultModel: 'flux',
  },
]

export const CATEGORY_TO_PRESET: Record<string, string> = {
  automotive: 'automotive',
  electronics: 'technology',
  fashion: 'fashion',
  beauty: 'beauty-cosmetics',
  cosmetics: 'beauty-cosmetics',
  health: 'healthcare',
  pharmacy: 'healthcare',
  technology: 'technology',
  home: 'furniture-home',
  furniture: 'furniture-home',
  construction: 'industrial',
  hardware: 'industrial',
  food: 'food-beverage',
  beverages: 'food-beverage',
  restaurant: 'food-beverage',
  education: 'corporate',
  sports: 'social-media',
  pets: 'social-media',
  toys: 'social-media',
  real_estate: 'real-estate',
  professional: 'corporate',
  financial: 'corporate',
  travel: 'social-media',
  industrial: 'industrial',
  entertainment: 'social-media',
  retail: 'commercial-advertising',
  nonprofit: 'corporate',
  other: 'commercial-advertising',
}

export const FORMAT_DIMENSIONS: Record<CreativeFormat, { width: number; height: number; label: string }> = {
  square:    { width: 1024, height: 1024, label: 'Cuadrado (1:1)' },
  landscape: { width: 1200, height: 630,  label: 'Horizontal (1.9:1)' },
  portrait:  { width: 1080, height: 1350, label: 'Vertical (4:5)' },
  story:     { width: 1080, height: 1920, label: 'Historia (9:16)' },
}

export const CREATIVE_MODELS: { value: CreativeModel; label: string }[] = [
  { value: 'flux',         label: 'FLUX (rápido)' },
  { value: 'flux-realism', label: 'FLUX Realism' },
  { value: 'flux-anime',   label: 'FLUX Anime' },
  { value: 'flux-3d',      label: 'FLUX 3D' },
  { value: 'turbo',        label: 'Turbo (ultra rápido)' },
]

// ── Plan configs ───────────────────────────────────────────────────────────────

export const PLAN_CONFIGS = [
  {
    name: 'starter' as const,
    displayName: 'Starter',
    price: 29,
    campaignLimit: 5,
    productLimit: 10,
    aiLimit: 20,
    metaLimit: 1,
    features: [
      '5 campañas activas',
      '10 productos',
      '20 generaciones IA/mes',
      '1 cuenta Meta Ads',
      'Soporte por email',
    ],
  },
  {
    name: 'professional' as const,
    displayName: 'Professional',
    price: 79,
    campaignLimit: 20,
    productLimit: 50,
    aiLimit: 100,
    metaLimit: 3,
    popular: true,
    features: [
      '20 campañas activas',
      '50 productos',
      '100 generaciones IA/mes',
      '3 cuentas Meta Ads',
      'Estadísticas avanzadas',
      'Soporte prioritario',
    ],
  },
  {
    name: 'agency' as const,
    displayName: 'Agency',
    price: 199,
    campaignLimit: -1,
    productLimit: -1,
    aiLimit: 500,
    metaLimit: 10,
    features: [
      'Campañas ilimitadas',
      'Productos ilimitados',
      '500 generaciones IA/mes',
      '10 cuentas Meta Ads',
      'API access',
      'White label',
      'Soporte dedicado',
    ],
  },
]
